### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by gydavid** [sindrebroch/esphome-walkingpad#1]
Hi, is this project dead?
This is a very good initiative :)

Thanks

**Comment by sindrebroch** [comment]
Hi, thanks :) It's not dead, but it might be a while until it is functional.

C++ and BLE GATT is new to me, and I have not set up my ESPHOME environment in a great way so development is slow and I only work on it sporadically. 

There are a few other projects that exists in controlling the walkingpads ([for example this](https://pypi.org/project/ph4-walkingpad/)), but none for ESPHOME as I have found.

Contributions are welcome :)
